controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

contact:
    path: /contact
    controller: App\Controller\PagesController::contact

cgu:
    path: /cgu
    controller: App\Controller\PagesController::cgu 